/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApiCustomerRouteImport } from './routes/api.customer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomerRoute = ApiCustomerRouteImport.update({
  id: '/api/customer',
  path: '/api/customer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/pricing': typeof PricingRoute
  '/terms': typeof TermsRoute
  '/about': typeof AboutRoute
  '/api/customer': typeof ApiCustomerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/pricing': typeof PricingRoute
  '/terms': typeof TermsRoute
  '/about': typeof AboutRoute
  '/api/customer': typeof ApiCustomerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/pricing': typeof PricingRoute
  '/terms': typeof TermsRoute
  '/about': typeof AboutRoute
  '/api/customer': typeof ApiCustomerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/account' | '/pricing' | '/terms' | '/about' | '/api/customer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/account' | '/pricing' | '/terms' | '/about' | '/api/customer'
  id: '__root__' | '/' | '/account' | '/pricing' | '/terms' | '/about' | '/api/customer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  PricingRoute: typeof PricingRoute
  TermsRoute: typeof TermsRoute
  AboutRoute: typeof AboutRoute
  ApiCustomerRoute: typeof ApiCustomerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer': {
      id: '/api/customer'
      path: '/api/customer'
      fullPath: '/api/customer'
      preLoaderRoute: typeof ApiCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  PricingRoute: PricingRoute,
  TermsRoute: TermsRoute,
  AboutRoute: AboutRoute,
  ApiCustomerRoute: ApiCustomerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
